# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89967332796a3b1ff52dc43ee55771f4"
name = "aeo-tracking"
application_url = "https://trackingsdk.shumbird.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events,read_products,read_inventory,read_legal_policies,read_locations"

[auth]
redirect_urls = [ "https://trackingsdk.shumbird.com/auth/callback" ]
